// <auto-generated/>
// 由 ExcelConfigCompiler [Server] 从 "D:\\LongLongGames\\game-match3-client\\Excel\\Shared\\CheckInReward.xlsx" / Sheet "CheckInReward" 生成。
// 不要手改这个文件——改 Excel 然后重新导表。
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Collections.Frozen;
using ExcelConfigCompiler.Runtime;

namespace Game.Shared.Config
{
    public readonly struct CheckInReward
    {
        public readonly int Id;
        public readonly int Day;
        public readonly int Energy;
        public readonly int ItemId1;
        public readonly int ItemCount1;
        public readonly int ItemId2;
        public readonly int ItemCount2;
        public readonly int ItemId3;
        public readonly int ItemCount3;
        public readonly string? Desc;

        public CheckInReward(ref ByteReader reader)
        {
            Id = reader.ReadInt32();
            Day = reader.ReadInt32();
            Energy = reader.ReadInt32();
            ItemId1 = reader.ReadInt32();
            ItemCount1 = reader.ReadInt32();
            ItemId2 = reader.ReadInt32();
            ItemCount2 = reader.ReadInt32();
            ItemId3 = reader.ReadInt32();
            ItemCount3 = reader.ReadInt32();
            Desc = reader.ReadString();
        }

        public static CheckInReward ReadJson(ref JsonReader reader)
        {
            int __Id = default;
            int __Day = default;
            int __Energy = default;
            int __ItemId1 = default;
            int __ItemCount1 = default;
            int __ItemId2 = default;
            int __ItemCount2 = default;
            int __ItemId3 = default;
            int __ItemCount3 = default;
            string? __Desc = default;
            reader.Expect('{');
            if (!reader.TryExpect('}'))
            {
                while (true)
                {
                    string name = reader.ReadPropertyName();
                    switch (name)
                    {
                        case "Id": __Id = reader.ReadInt32(); break;
                        case "Day": __Day = reader.ReadInt32(); break;
                        case "Energy": __Energy = reader.ReadInt32(); break;
                        case "ItemId1": __ItemId1 = reader.ReadInt32(); break;
                        case "ItemCount1": __ItemCount1 = reader.ReadInt32(); break;
                        case "ItemId2": __ItemId2 = reader.ReadInt32(); break;
                        case "ItemCount2": __ItemCount2 = reader.ReadInt32(); break;
                        case "ItemId3": __ItemId3 = reader.ReadInt32(); break;
                        case "ItemCount3": __ItemCount3 = reader.ReadInt32(); break;
                        case "Desc": __Desc = reader.ReadString(); break;
                        default: reader.SkipValue(); break;
                    }
                    if (reader.TryExpect('}')) break;
                    reader.Expect(',');
                }
            }
            return new CheckInReward(
                __Id,
                __Day,
                __Energy,
                __ItemId1,
                __ItemCount1,
                __ItemId2,
                __ItemCount2,
                __ItemId3,
                __ItemCount3,
                __Desc
            );
        }

        private CheckInReward(int Id, int Day, int Energy, int ItemId1, int ItemCount1, int ItemId2, int ItemCount2, int ItemId3, int ItemCount3, string? Desc)
        {
            this.Id = Id;
            this.Day = Day;
            this.Energy = Energy;
            this.ItemId1 = ItemId1;
            this.ItemCount1 = ItemCount1;
            this.ItemId2 = ItemId2;
            this.ItemCount2 = ItemCount2;
            this.ItemId3 = ItemId3;
            this.ItemCount3 = ItemCount3;
            this.Desc = Desc;
        }

        public void Write(ByteWriter writer)
        {
            writer.WriteInt32(Id);
            writer.WriteInt32(Day);
            writer.WriteInt32(Energy);
            writer.WriteInt32(ItemId1);
            writer.WriteInt32(ItemCount1);
            writer.WriteInt32(ItemId2);
            writer.WriteInt32(ItemCount2);
            writer.WriteInt32(ItemId3);
            writer.WriteInt32(ItemCount3);
            writer.WriteString(Desc);
        }
    }

    public static class CheckInRewardTable
    {
        public static CheckInReward[] Load(byte[] data)
        {
            var reader = new ByteReader(data);
            if (!reader.ReadMagicMatches(BinaryFormat.Magic))
                throw new InvalidDataException("CheckInReward.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。");
            int version = reader.ReadInt32();
            if (version != BinaryFormat.CurrentVersion)
                throw new InvalidDataException($"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。");
            int count = reader.ReadInt32();
            var result = new CheckInReward[count];
            for (int i = 0; i < count; i++)
                result[i] = new CheckInReward(ref reader);
            return result;
        }

        public static CheckInReward[] LoadJson(string json)
        {
            var reader = new JsonReader(json);
            reader.Expect('[');
            if (reader.TryExpect(']')) return Array.Empty<CheckInReward>();
            var list = new List<CheckInReward>(64);
            while (true)
            {
                list.Add(CheckInReward.ReadJson(ref reader));
                if (reader.TryExpect(']')) break;
                reader.Expect(',');
            }
            return list.ToArray();
        }

        public static CheckInReward[] LoadJsonFromFile(string path)
            => LoadJson(File.ReadAllText(path));

        private static CheckInReward[]? _cache;
        private static FrozenDictionary<int, int>? _indexById;

        public static CheckInReward[] LoadAndCache(byte[] data)
        {
            _cache = Load(data);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        public static CheckInReward[] LoadJsonAndCache(string json)
        {
            _cache = LoadJson(json);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        /// <summary>查询阶段不产生 GC（返回值拷贝）。需先 LoadAndCache / LoadJsonAndCache。</summary>
        public static CheckInReward Get(int id)
        {
            if (_cache == null || _indexById == null)
                throw new InvalidOperationException("CheckInRewardTable 尚未 LoadAndCache。");
            if (_indexById.TryGetValue(id, out var idx))
                return _cache[idx];
            throw new KeyNotFoundException($"CheckInReward: 找不到 id={id}");
        }

        public static bool TryGet(int id, out CheckInReward value)
        {
            value = default;
            if (_cache == null || _indexById == null) return false;
            if (!_indexById.TryGetValue(id, out var idx)) return false;
            value = _cache[idx];
            return true;
        }

        public static CheckInReward[]? Cache => _cache;
    }
}
