// <auto-generated/>
// 由 ExcelConfigCompiler [Server] 从 "D:\\LongLongGames\\game-match3-client\\Excel\\Shared\\CheckInReward.xlsx" / Sheet "CheckInReward" 生成。
// 不要手改这个文件——改 Excel 然后重新导表。
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Collections.Frozen;
using ExcelConfigCompiler.Runtime;

namespace Game.Shared.Config
{
    public readonly struct CheckInReward
    {
        public readonly int Id;
        public readonly int Day;
        public readonly int Energy;
        public readonly int ItemId1;
        public readonly int ItemCount1;
        public readonly int ItemId2;
        public readonly int ItemCount2;
        public readonly int ItemId3;
        public readonly int ItemCount3;
        public readonly string? Desc;

        public CheckInReward(ref ByteReader reader)
        {
            Id = reader.ReadInt32();
            Day = reader.ReadInt32();
            Energy = reader.ReadInt32();
            ItemId1 = reader.ReadInt32();
            ItemCount1 = reader.ReadInt32();
            ItemId2 = reader.ReadInt32();
            ItemCount2 = reader.ReadInt32();
            ItemId3 = reader.ReadInt32();
            ItemCount3 = reader.ReadInt32();
            Desc = reader.ReadString();
        }

        public void Write(ByteWriter writer)
        {
            writer.WriteInt32(Id);
            writer.WriteInt32(Day);
            writer.WriteInt32(Energy);
            writer.WriteInt32(ItemId1);
            writer.WriteInt32(ItemCount1);
            writer.WriteInt32(ItemId2);
            writer.WriteInt32(ItemCount2);
            writer.WriteInt32(ItemId3);
            writer.WriteInt32(ItemCount3);
            writer.WriteString(Desc);
        }
    }

    public static class CheckInRewardTable
    {
        public static CheckInReward[] Load(byte[] data)
        {
            var reader = new ByteReader(data);
            if (!reader.ReadMagicMatches(BinaryFormat.Magic))
                throw new InvalidDataException("CheckInReward.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。");
            int version = reader.ReadInt32();
            if (version != BinaryFormat.CurrentVersion)
                throw new InvalidDataException($"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。");
            int count = reader.ReadInt32();
            var result = new CheckInReward[count];
            for (int i = 0; i < count; i++)
                result[i] = new CheckInReward(ref reader);
            return result;
        }

        private static CheckInReward[]? _cache;
        private static FrozenDictionary<int, int>? _indexById;

        public static CheckInReward[] LoadAndCache(byte[] data)
        {
            _cache = Load(data);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        /// <summary>查询阶段不产生 GC（返回值拷贝）。需先 LoadAndCache。</summary>
        public static CheckInReward Get(int id)
        {
            if (_cache == null || _indexById == null)
                throw new InvalidOperationException("CheckInRewardTable 尚未 LoadAndCache。");
            if (_indexById.TryGetValue(id, out var idx))
                return _cache[idx];
            throw new KeyNotFoundException($"CheckInReward: 找不到 id={id}");
        }

        public static bool TryGet(int id, out CheckInReward value)
        {
            value = default;
            if (_cache == null || _indexById == null) return false;
            if (!_indexById.TryGetValue(id, out var idx)) return false;
            value = _cache[idx];
            return true;
        }

        public static CheckInReward[]? Cache => _cache;
    }
}
