// <auto-generated/>
// 由 ExcelConfigCompiler [Server] 从 "D:\\LongLongGames\\game-match3-client\\Excel\\Shared\\GameRules.xlsx" / Sheet "GameRules" 生成。
// 不要手改这个文件——改 Excel 然后重新导表。
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Collections.Frozen;
using ExcelConfigCompiler.Runtime;

namespace Game.Shared.Config
{
    public readonly struct GameRules
    {
        public readonly int Id;
        public readonly int EnergyMax;
        public readonly int EnergyCostPerPlay;
        public readonly int EnergyRegenSeconds;
        public readonly int LevelsPerMap;
        public readonly int MapUnlockClearCount;
        public readonly int GoldPerStar;
        public readonly int MinStarsToUnlockNextLevel;
        public readonly bool ValidateLevelExists;
        public readonly bool ValidateStepsAgainstConfig;
        public readonly string? Desc;

        public GameRules(ref ByteReader reader)
        {
            Id = reader.ReadInt32();
            EnergyMax = reader.ReadInt32();
            EnergyCostPerPlay = reader.ReadInt32();
            EnergyRegenSeconds = reader.ReadInt32();
            LevelsPerMap = reader.ReadInt32();
            MapUnlockClearCount = reader.ReadInt32();
            GoldPerStar = reader.ReadInt32();
            MinStarsToUnlockNextLevel = reader.ReadInt32();
            ValidateLevelExists = reader.ReadBoolean();
            ValidateStepsAgainstConfig = reader.ReadBoolean();
            Desc = reader.ReadString();
        }

        public void Write(ByteWriter writer)
        {
            writer.WriteInt32(Id);
            writer.WriteInt32(EnergyMax);
            writer.WriteInt32(EnergyCostPerPlay);
            writer.WriteInt32(EnergyRegenSeconds);
            writer.WriteInt32(LevelsPerMap);
            writer.WriteInt32(MapUnlockClearCount);
            writer.WriteInt32(GoldPerStar);
            writer.WriteInt32(MinStarsToUnlockNextLevel);
            writer.WriteBoolean(ValidateLevelExists);
            writer.WriteBoolean(ValidateStepsAgainstConfig);
            writer.WriteString(Desc);
        }
    }

    public static class GameRulesTable
    {
        public static GameRules[] Load(byte[] data)
        {
            var reader = new ByteReader(data);
            if (!reader.ReadMagicMatches(BinaryFormat.Magic))
                throw new InvalidDataException("GameRules.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。");
            int version = reader.ReadInt32();
            if (version != BinaryFormat.CurrentVersion)
                throw new InvalidDataException($"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。");
            int count = reader.ReadInt32();
            var result = new GameRules[count];
            for (int i = 0; i < count; i++)
                result[i] = new GameRules(ref reader);
            return result;
        }

        private static GameRules[]? _cache;
        private static FrozenDictionary<int, int>? _indexById;

        public static GameRules[] LoadAndCache(byte[] data)
        {
            _cache = Load(data);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        /// <summary>查询阶段不产生 GC（返回值拷贝）。需先 LoadAndCache。</summary>
        public static GameRules Get(int id)
        {
            if (_cache == null || _indexById == null)
                throw new InvalidOperationException("GameRulesTable 尚未 LoadAndCache。");
            if (_indexById.TryGetValue(id, out var idx))
                return _cache[idx];
            throw new KeyNotFoundException($"GameRules: 找不到 id={id}");
        }

        public static bool TryGet(int id, out GameRules value)
        {
            value = default;
            if (_cache == null || _indexById == null) return false;
            if (!_indexById.TryGetValue(id, out var idx)) return false;
            value = _cache[idx];
            return true;
        }

        public static GameRules[]? Cache => _cache;
    }
}
