// <auto-generated/>
// 由 ExcelConfigCompiler [Server] 从 "D:\\LongLongGames\\game-match3-client\\Excel\\Shared\\Item.xlsx" / Sheet "Item" 生成。
// 不要手改这个文件——改 Excel 然后重新导表。
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Collections.Frozen;
using ExcelConfigCompiler.Runtime;

namespace Game.Shared.Config
{
    public readonly struct Item
    {
        public readonly int Id;
        public readonly string? Name;
        public readonly string? Effect;
        public readonly int Param;
        public readonly string? Icon;
        public readonly string? Desc;

        public Item(ref ByteReader reader)
        {
            Id = reader.ReadInt32();
            Name = reader.ReadString();
            Effect = reader.ReadString();
            Param = reader.ReadInt32();
            Icon = reader.ReadString();
            Desc = reader.ReadString();
        }

        public static Item ReadJson(ref JsonReader reader)
        {
            int __Id = default;
            string? __Name = default;
            string? __Effect = default;
            int __Param = default;
            string? __Icon = default;
            string? __Desc = default;
            reader.Expect('{');
            if (!reader.TryExpect('}'))
            {
                while (true)
                {
                    string name = reader.ReadPropertyName();
                    switch (name)
                    {
                        case "Id": __Id = reader.ReadInt32(); break;
                        case "Name": __Name = reader.ReadString(); break;
                        case "Effect": __Effect = reader.ReadString(); break;
                        case "Param": __Param = reader.ReadInt32(); break;
                        case "Icon": __Icon = reader.ReadString(); break;
                        case "Desc": __Desc = reader.ReadString(); break;
                        default: reader.SkipValue(); break;
                    }
                    if (reader.TryExpect('}')) break;
                    reader.Expect(',');
                }
            }
            return new Item(
                __Id,
                __Name,
                __Effect,
                __Param,
                __Icon,
                __Desc
            );
        }

        private Item(int Id, string? Name, string? Effect, int Param, string? Icon, string? Desc)
        {
            this.Id = Id;
            this.Name = Name;
            this.Effect = Effect;
            this.Param = Param;
            this.Icon = Icon;
            this.Desc = Desc;
        }

        public void Write(ByteWriter writer)
        {
            writer.WriteInt32(Id);
            writer.WriteString(Name);
            writer.WriteString(Effect);
            writer.WriteInt32(Param);
            writer.WriteString(Icon);
            writer.WriteString(Desc);
        }
    }

    public static class ItemTable
    {
        public static Item[] Load(byte[] data)
        {
            var reader = new ByteReader(data);
            if (!reader.ReadMagicMatches(BinaryFormat.Magic))
                throw new InvalidDataException("Item.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。");
            int version = reader.ReadInt32();
            if (version != BinaryFormat.CurrentVersion)
                throw new InvalidDataException($"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。");
            int count = reader.ReadInt32();
            var result = new Item[count];
            for (int i = 0; i < count; i++)
                result[i] = new Item(ref reader);
            return result;
        }

        public static Item[] LoadJson(string json)
        {
            var reader = new JsonReader(json);
            reader.Expect('[');
            if (reader.TryExpect(']')) return Array.Empty<Item>();
            var list = new List<Item>(64);
            while (true)
            {
                list.Add(Item.ReadJson(ref reader));
                if (reader.TryExpect(']')) break;
                reader.Expect(',');
            }
            return list.ToArray();
        }

        public static Item[] LoadJsonFromFile(string path)
            => LoadJson(File.ReadAllText(path));

        private static Item[]? _cache;
        private static FrozenDictionary<int, int>? _indexById;

        public static Item[] LoadAndCache(byte[] data)
        {
            _cache = Load(data);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        public static Item[] LoadJsonAndCache(string json)
        {
            _cache = LoadJson(json);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        /// <summary>查询阶段不产生 GC（返回值拷贝）。需先 LoadAndCache / LoadJsonAndCache。</summary>
        public static Item Get(int id)
        {
            if (_cache == null || _indexById == null)
                throw new InvalidOperationException("ItemTable 尚未 LoadAndCache。");
            if (_indexById.TryGetValue(id, out var idx))
                return _cache[idx];
            throw new KeyNotFoundException($"Item: 找不到 id={id}");
        }

        public static bool TryGet(int id, out Item value)
        {
            value = default;
            if (_cache == null || _indexById == null) return false;
            if (!_indexById.TryGetValue(id, out var idx)) return false;
            value = _cache[idx];
            return true;
        }

        public static Item[]? Cache => _cache;
    }
}
