// <auto-generated/>
// 由 ExcelConfigCompiler [Server] 从 "D:\\LongLongGames\\game-match3-client\\Excel\\Shared\\Item.xlsx" / Sheet "Item" 生成。
// 不要手改这个文件——改 Excel 然后重新导表。
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Collections.Frozen;
using ExcelConfigCompiler.Runtime;

namespace Game.Shared.Config
{
    public readonly struct Item
    {
        public readonly int Id;
        public readonly string? Name;
        public readonly string? Effect;
        public readonly int Param;
        public readonly string? Icon;
        public readonly string? Desc;

        public Item(ref ByteReader reader)
        {
            Id = reader.ReadInt32();
            Name = reader.ReadString();
            Effect = reader.ReadString();
            Param = reader.ReadInt32();
            Icon = reader.ReadString();
            Desc = reader.ReadString();
        }

        public void Write(ByteWriter writer)
        {
            writer.WriteInt32(Id);
            writer.WriteString(Name);
            writer.WriteString(Effect);
            writer.WriteInt32(Param);
            writer.WriteString(Icon);
            writer.WriteString(Desc);
        }
    }

    public static class ItemTable
    {
        public static Item[] Load(byte[] data)
        {
            var reader = new ByteReader(data);
            if (!reader.ReadMagicMatches(BinaryFormat.Magic))
                throw new InvalidDataException("Item.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。");
            int version = reader.ReadInt32();
            if (version != BinaryFormat.CurrentVersion)
                throw new InvalidDataException($"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。");
            int count = reader.ReadInt32();
            var result = new Item[count];
            for (int i = 0; i < count; i++)
                result[i] = new Item(ref reader);
            return result;
        }

        private static Item[]? _cache;
        private static FrozenDictionary<int, int>? _indexById;

        public static Item[] LoadAndCache(byte[] data)
        {
            _cache = Load(data);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        /// <summary>查询阶段不产生 GC（返回值拷贝）。需先 LoadAndCache。</summary>
        public static Item Get(int id)
        {
            if (_cache == null || _indexById == null)
                throw new InvalidOperationException("ItemTable 尚未 LoadAndCache。");
            if (_indexById.TryGetValue(id, out var idx))
                return _cache[idx];
            throw new KeyNotFoundException($"Item: 找不到 id={id}");
        }

        public static bool TryGet(int id, out Item value)
        {
            value = default;
            if (_cache == null || _indexById == null) return false;
            if (!_indexById.TryGetValue(id, out var idx)) return false;
            value = _cache[idx];
            return true;
        }

        public static Item[]? Cache => _cache;
    }
}
