// <auto-generated/>
// 由 ExcelConfigCompiler [Server] 从 "D:\\LongLongGames\\game-match3-client\\Excel\\Shared\\Level.xlsx" / Sheet "Level" 生成。
// 不要手改这个文件——改 Excel 然后重新导表。
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Collections.Frozen;
using ExcelConfigCompiler.Runtime;

namespace Game.Shared.Config
{
    public readonly struct Level
    {
        public readonly int Id;
        public readonly int MapId;
        public readonly int LevelId;
        public readonly int MaxSteps;
        public readonly int StepsFor3Stars;
        public readonly int StepsFor2Stars;
        public readonly int BoardWidth;
        public readonly int BoardHeight;
        public readonly string? Goal;
        public readonly int GoalValue;

        public Level(ref ByteReader reader)
        {
            Id = reader.ReadInt32();
            MapId = reader.ReadInt32();
            LevelId = reader.ReadInt32();
            MaxSteps = reader.ReadInt32();
            StepsFor3Stars = reader.ReadInt32();
            StepsFor2Stars = reader.ReadInt32();
            BoardWidth = reader.ReadInt32();
            BoardHeight = reader.ReadInt32();
            Goal = reader.ReadString();
            GoalValue = reader.ReadInt32();
        }

        public static Level ReadJson(ref JsonReader reader)
        {
            int __Id = default;
            int __MapId = default;
            int __LevelId = default;
            int __MaxSteps = default;
            int __StepsFor3Stars = default;
            int __StepsFor2Stars = default;
            int __BoardWidth = default;
            int __BoardHeight = default;
            string? __Goal = default;
            int __GoalValue = default;
            reader.Expect('{');
            if (!reader.TryExpect('}'))
            {
                while (true)
                {
                    string name = reader.ReadPropertyName();
                    switch (name)
                    {
                        case "Id": __Id = reader.ReadInt32(); break;
                        case "MapId": __MapId = reader.ReadInt32(); break;
                        case "LevelId": __LevelId = reader.ReadInt32(); break;
                        case "MaxSteps": __MaxSteps = reader.ReadInt32(); break;
                        case "StepsFor3Stars": __StepsFor3Stars = reader.ReadInt32(); break;
                        case "StepsFor2Stars": __StepsFor2Stars = reader.ReadInt32(); break;
                        case "BoardWidth": __BoardWidth = reader.ReadInt32(); break;
                        case "BoardHeight": __BoardHeight = reader.ReadInt32(); break;
                        case "Goal": __Goal = reader.ReadString(); break;
                        case "GoalValue": __GoalValue = reader.ReadInt32(); break;
                        default: reader.SkipValue(); break;
                    }
                    if (reader.TryExpect('}')) break;
                    reader.Expect(',');
                }
            }
            return new Level(
                __Id,
                __MapId,
                __LevelId,
                __MaxSteps,
                __StepsFor3Stars,
                __StepsFor2Stars,
                __BoardWidth,
                __BoardHeight,
                __Goal,
                __GoalValue
            );
        }

        private Level(int Id, int MapId, int LevelId, int MaxSteps, int StepsFor3Stars, int StepsFor2Stars, int BoardWidth, int BoardHeight, string? Goal, int GoalValue)
        {
            this.Id = Id;
            this.MapId = MapId;
            this.LevelId = LevelId;
            this.MaxSteps = MaxSteps;
            this.StepsFor3Stars = StepsFor3Stars;
            this.StepsFor2Stars = StepsFor2Stars;
            this.BoardWidth = BoardWidth;
            this.BoardHeight = BoardHeight;
            this.Goal = Goal;
            this.GoalValue = GoalValue;
        }

        public void Write(ByteWriter writer)
        {
            writer.WriteInt32(Id);
            writer.WriteInt32(MapId);
            writer.WriteInt32(LevelId);
            writer.WriteInt32(MaxSteps);
            writer.WriteInt32(StepsFor3Stars);
            writer.WriteInt32(StepsFor2Stars);
            writer.WriteInt32(BoardWidth);
            writer.WriteInt32(BoardHeight);
            writer.WriteString(Goal);
            writer.WriteInt32(GoalValue);
        }
    }

    public static class LevelTable
    {
        public static Level[] Load(byte[] data)
        {
            var reader = new ByteReader(data);
            if (!reader.ReadMagicMatches(BinaryFormat.Magic))
                throw new InvalidDataException("Level.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。");
            int version = reader.ReadInt32();
            if (version != BinaryFormat.CurrentVersion)
                throw new InvalidDataException($"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。");
            int count = reader.ReadInt32();
            var result = new Level[count];
            for (int i = 0; i < count; i++)
                result[i] = new Level(ref reader);
            return result;
        }

        public static Level[] LoadJson(string json)
        {
            var reader = new JsonReader(json);
            reader.Expect('[');
            if (reader.TryExpect(']')) return Array.Empty<Level>();
            var list = new List<Level>(64);
            while (true)
            {
                list.Add(Level.ReadJson(ref reader));
                if (reader.TryExpect(']')) break;
                reader.Expect(',');
            }
            return list.ToArray();
        }

        public static Level[] LoadJsonFromFile(string path)
            => LoadJson(File.ReadAllText(path));

        private static Level[]? _cache;
        private static FrozenDictionary<int, int>? _indexById;

        public static Level[] LoadAndCache(byte[] data)
        {
            _cache = Load(data);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        public static Level[] LoadJsonAndCache(string json)
        {
            _cache = LoadJson(json);
            var builder = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                builder[_cache[i].Id] = i;
            _indexById = builder.ToFrozenDictionary();
            return _cache;
        }

        /// <summary>查询阶段不产生 GC（返回值拷贝）。需先 LoadAndCache / LoadJsonAndCache。</summary>
        public static Level Get(int id)
        {
            if (_cache == null || _indexById == null)
                throw new InvalidOperationException("LevelTable 尚未 LoadAndCache。");
            if (_indexById.TryGetValue(id, out var idx))
                return _cache[idx];
            throw new KeyNotFoundException($"Level: 找不到 id={id}");
        }

        public static bool TryGet(int id, out Level value)
        {
            value = default;
            if (_cache == null || _indexById == null) return false;
            if (!_indexById.TryGetValue(id, out var idx)) return false;
            value = _cache[idx];
            return true;
        }

        public static Level[]? Cache => _cache;
    }
}
